### ISSUE TITLE
[Support]: Integration won't start after upgrade HA OS Core to V2021.12

### ISSUE THREAD

**Issue by johanvh83** [blakeblackshear/frigate#2430]
### Describe the problem you are having

After upgrade of Core to V2021.12 the integration gives below notification:
<img width="476" alt="Schermafbeelding 2021-12-11 om 21 42 05" src="https://user-images.githubusercontent.com/76775686/145691034-282a3fe4-6bdb-41ff-9c5f-e4795a40287a.png">

Anyway, the integration starts and works.

The log shows:

Logger: homeassistant.setup
Source: setup.py:153
First occurred: 9:36:28 PM (1 occurrences)
Last logged: 9:36:28 PM

Setup failed for frigate: Unable to import component: cannot import name 'HTTP_BAD_REQUEST' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

### Version

core-2021.12.0

### Frigate config file

```yaml
mqtt:
  host: 192.168.100.146
  user: mqtt_zigbee_user
  password: blablabla

cameras:
  voortuin_garage:
    ffmpeg:
      inputs: 
        - path: rtsp://admin:XVRHRD@192.168.100.145:554/h264_stream
          roles:
            - detect
            - clips
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 2
    motion:
      mask:
        - 0,0,1920,0,1920,213,1454,153,1449,99,1088,173,671,310,718,399,294,586,278,516,0,671
          
  tuin:
    ffmpeg:
      inputs: 
        - path: rtsp://admin:MTZJGK@192.168.100.108:554/h264_stream
          roles:
            - detect
            - clips
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 2
    motion:
      mask:
        - 1920,0,1920,0,1920,375,1436,378,1446,450,1345,457,1270,0
        - 251,494,375,453,343,211,429,0,328,0,198,117,173,426,229,400

  voortuin:
    ffmpeg:
      inputs: 
        - path: rtsp://admin:1Caa2Jar@192.168.100.125:554/h264_stream
          roles:
            - detect
            - clips
    detect:
      width: 3840
      height: 2160
      fps: 5
    objects:
      track:
        - person
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 2
    motion:
      mask:
        - 0,440,776,455,794,642,1259,675,1858,765,2511,898,2515,1082,3420,1429,3590,1432,3615,1072,3840,1108,3817,0,0,0
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2021-12-11 21:37:05] frigate.app                    INFO    : Starting Frigate (0.9.4-26ae608)
[2021-12-11 21:37:05] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2021-12-11 21:37:05] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2021-12-11 21:37:05] peewee_migrate                 INFO    : There is nothing to migrate
[2021-12-11 21:37:05] frigate.mqtt                   INFO    : MQTT connected
[2021-12-11 21:37:05] frigate.app                    INFO    : Output process started: 216
[2021-12-11 21:37:05] detector.cpu1                  INFO    : Starting detection process: 214
[2021-12-11 21:37:05] detector.cpu2                  INFO    : Starting detection process: 215
[2021-12-11 21:37:05] frigate.app                    INFO    : Camera processor started for voortuin_garage: 219
[2021-12-11 21:37:05] ws4py                          INFO    : Using epoll
[2021-12-11 21:37:05] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
[2021-12-11 21:37:05] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
[2021-12-11 21:37:05] frigate.app                    INFO    : Camera processor started for tuin: 223
[2021-12-11 21:37:05] frigate.app                    INFO    : Camera processor started for voortuin: 224
[2021-12-11 21:37:05] frigate.app                    INFO    : Capture process started for voortuin_garage: 226
[2021-12-11 21:37:06] frigate.app                    INFO    : Capture process started for tuin: 229
[2021-12-11 21:37:06] frigate.app                    INFO    : Capture process started for voortuin: 230
[2021-12-11 21:37:06] ws4py                          INFO    : Using epoll
[2021-12-11 21:41:35] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:56240]
[2021-12-11 21:41:37] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | 
Remote => 127.0.0.1:56240]
[2021-12-11 21:41:37] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:56262]
[2021-12-11 21:41:43] frigate.mqtt                   INFO    : Turning off snapshots for tuin via mqtt
[2021-12-11 21:41:45] frigate.mqtt                   INFO    : Turning off snapshots for voortuin_garage via mqtt
[2021-12-11 21:41:46] frigate.mqtt                   INFO    : Turning off snapshots for voortuin via mqtt
[2021-12-11 21:43:17] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:56262]
```

### FFprobe output from your camera

```shell
Not relevant for this issue and as far as I know, not possible in my install method
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Mixed

### Camera make and model

hikvision and izviz

### Any other information that may be helpful

Restarted HA completely but same notification appeared.
CPU load is very high, before the update it was no issue
<img width="1009" alt="Schermafbeelding 2021-12-11 om 21 49 27" src="https://user-images.githubusercontent.com/76775686/145691199-0f76da18-5988-4322-b905-16f884fe60af.png">
<img width="408" alt="Schermafbeelding 2021-12-11 om 21 50 29" src="https://user-images.githubusercontent.com/76775686/145691222-3276ec01-2d72-4c2b-bdb3-110bae2dd610.png">
.

**Comment by blakeblackshear** [comment]
https://github.com/blakeblackshear/frigate-hass-integration/releases/tag/v2.2.0

**Comment by Klagio** [comment]
How to download the latest release that fixes the issue?

**Comment by johanvh83** [comment]
Thanks, the new release fixed the problem.

**Comment by bg1000** [comment]
For anyone else seeing this and having trouble with the new version this did not work for me until I (after restoring to 2021-11.X from backup):
- Upgraded home assistant.
- Deleted the frigate integration (from home assistant not from HACS)
- Updated the frigate integration in HACS
- Added the frigate integration to home assistant and configured the frigate address.
- Restarted home assistant
